# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
        - 5432:5432
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
